# Generated by Django 6.0 on 2025-12-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Causal Leave'), ('SICK', 'Sick Leave'), ('PAID', 'Paid Leave')], max_length=20),
        ),
    ]
