# Generated by Django 6.0 on 2025-12-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='used_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
